/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KiWorkflowCheckRouteImport } from './routes/ki-workflow-check'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AiNoobClubAnmeldungRouteImport } from './routes/ai-noob-club-anmeldung'
import { Route as AiNoobClubRouteImport } from './routes/ai-noob-club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as ApiPublicSignupRouteImport } from './routes/api/public/signup'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KiWorkflowCheckRoute = KiWorkflowCheckRouteImport.update({
  id: '/ki-workflow-check',
  path: '/ki-workflow-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNoobClubAnmeldungRoute = AiNoobClubAnmeldungRouteImport.update({
  id: '/ai-noob-club-anmeldung',
  path: '/ai-noob-club-anmeldung',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNoobClubRoute = AiNoobClubRouteImport.update({
  id: '/ai-noob-club',
  path: '/ai-noob-club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignupRoute = ApiPublicSignupRouteImport.update({
  id: '/api/public/signup',
  path: '/api/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-noob-club': typeof AiNoobClubRoute
  '/ai-noob-club-anmeldung': typeof AiNoobClubAnmeldungRoute
  '/impressum': typeof ImpressumRoute
  '/ki-workflow-check': typeof KiWorkflowCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-noob-club': typeof AiNoobClubRoute
  '/ai-noob-club-anmeldung': typeof AiNoobClubAnmeldungRoute
  '/impressum': typeof ImpressumRoute
  '/ki-workflow-check': typeof KiWorkflowCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-noob-club': typeof AiNoobClubRoute
  '/ai-noob-club-anmeldung': typeof AiNoobClubAnmeldungRoute
  '/impressum': typeof ImpressumRoute
  '/ki-workflow-check': typeof KiWorkflowCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-noob-club'
    | '/ai-noob-club-anmeldung'
    | '/impressum'
    | '/ki-workflow-check'
    | '/sitemap.xml'
    | '/api/public/signup'
    | '/api/public/waitlist'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-noob-club'
    | '/ai-noob-club-anmeldung'
    | '/impressum'
    | '/ki-workflow-check'
    | '/sitemap.xml'
    | '/api/public/signup'
    | '/api/public/waitlist'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/ai-noob-club'
    | '/ai-noob-club-anmeldung'
    | '/impressum'
    | '/ki-workflow-check'
    | '/sitemap.xml'
    | '/api/public/signup'
    | '/api/public/waitlist'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiNoobClubRoute: typeof AiNoobClubRoute
  AiNoobClubAnmeldungRoute: typeof AiNoobClubAnmeldungRoute
  ImpressumRoute: typeof ImpressumRoute
  KiWorkflowCheckRoute: typeof KiWorkflowCheckRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSignupRoute: typeof ApiPublicSignupRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ki-workflow-check': {
      id: '/ki-workflow-check'
      path: '/ki-workflow-check'
      fullPath: '/ki-workflow-check'
      preLoaderRoute: typeof KiWorkflowCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-noob-club-anmeldung': {
      id: '/ai-noob-club-anmeldung'
      path: '/ai-noob-club-anmeldung'
      fullPath: '/ai-noob-club-anmeldung'
      preLoaderRoute: typeof AiNoobClubAnmeldungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-noob-club': {
      id: '/ai-noob-club'
      path: '/ai-noob-club'
      fullPath: '/ai-noob-club'
      preLoaderRoute: typeof AiNoobClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signup': {
      id: '/api/public/signup'
      path: '/api/public/signup'
      fullPath: '/api/public/signup'
      preLoaderRoute: typeof ApiPublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiNoobClubRoute: AiNoobClubRoute,
  AiNoobClubAnmeldungRoute: AiNoobClubAnmeldungRoute,
  ImpressumRoute: ImpressumRoute,
  KiWorkflowCheckRoute: KiWorkflowCheckRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSignupRoute: ApiPublicSignupRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
